POST http://localhost:9006/mock/cihub HTTP/1.1
Content-Type: application/json

{"BusMsg":{"AppHdr":{"Fr":{"FIId":{"FinInstnId":{"Othr":{"Id":"SIHBIDJ1"}}}},"To":{"FIId":{"FinInstnId":{"Othr":{"Id":"FASTIDJA"}}}},"BizMsgIdr":"20220723SIHBIDJ1000O9976923580","MsgDefIdr":"pacs.028.001.04","CreDt":"2022-07-23T14:22:18Z"},"Document":{"FIToFIPmtStsReq":{"GrpHdr":{"MsgId":"20220723SIHBIDJ100076923580","CreDtTm":"2022-07-23T21:22:18.159"},"TxInf":[{"OrgnlEndToEndId":"20211212SIHBIDJ1110O0200000594"}]}}}}
