POST http://10.11.103.65:9006/mock/inbound HTTP/1.1
Content-Type: application/json

{
    "PaymentRequest": {
        "amount": "33000",
        "debtorName": "Anton A",
        "debtorAccountNo": "22333451",
        "creditorAccountNo": "2388807350641",
        "paymentInfo": "creditreject"
    }
}
