POST http://localhost:9006/mock/cihub HTTP/1.1
Content-Type: application/json

{
  "BusMsg": {
    "AppHdr": {
      "Fr": {
        "Fiid": {
          "FinInstnId": {
            "Othr": {
              "Id": "SIHBIDJ1"
            }
          }
        }
      },
      "To": {
        "Fiid": {
          "FinInstnId": {
            "Othr": {
              "Id": "INDOIDJA"
            }
          }
        }
      },
      "BizMsgIdr": "20211112SIHBIDJ1610O0100000199",
      "MsgDefIdr": "prxy.003.001.01",
      "CreDt": "2021-11-12T04:17:22Z"
    },
    "Document": {
      "PrxyLookUp": {
        "GrpHdr": {
          "MsgId": "20211112SIHBIDJ161000000199",
          "CreDtTm": "2021-11-12T11:17:22.537",
          "MsgSndr": {
            "Agt": {
              "FinInstnId": {
                "Othr": {
                  "Id": "SIHBIDJ1"
                }
              }
            },
            "Acct": {
              "Id": {
                "Othr": {
                  "Id": "22341111"
                }
              }
            }
          }
        },
        "LookUp": {
          "PrxyOnly": {
            "LkUpTp": "PXRS",
            "Id": "20211112SIHBIDJ100000199",
            "PrxyRtrvl": {
              "Tp": "02",
              "Val": "yogi@gmail.com"
            }
          }
        }
      }
    }
  }
}

###


{"BusMsg":{"AppHdr":{"Fr":{"Fiid":{"FinInstnId":{"Othr":{"Id":"SIHBIDJ1"}}}},"To":{"Fiid":{"FinInstnId":{"Othr":{"Id":"BMNDIDJA"}}}},"BizMsgIdr":"20211031SIHBIDJ1010O0130400054","MsgDefIdr":"pacs.008.001.08","CreDt":"2021-10-31T09:41:39"},"Document":{"FitoFIPmtStsReq":{"GrpHdr":{"MsgId":"20211031SIHBIDJ101030300405","CreDtTm":1635648099683},"TxInf":[{"OrgnlEndToEndId":"20211030SIHBIDJ1010O0130300407"}]}}}}
