POST http://localhost:9006/mock/cihub HTTP/1.1
Content-Type: application/json

{
  "BusMsg": {
    "AppHdr": {
      "Fr": {
        "Fiid": {
          "FinInstnId": {
            "Othr": {
              "Id": "FASTIDJA"
            }
          }
        }
      },
      "To": {
        "Fiid": {
          "FinInstnId": {
            "Othr": {
              "Id": "INDOIDJA"
            }
          }
        }
      },
      "BizMsgIdr": "20210826FASTIDJA710O0100000167",
      "MsgDefIdr": "prxy.001.001.01",
      "CreDt": "2021-08-26T12:06:17"
    },
    "Document": {
      "PrxyRegn": {
        "GrpHdr": {
          "MsgId": "20210826FASTIDJA71000000168",
          "CreDtTm": "2021-08-26T12:06:17",
          "MsgSndr": {
            "Agt": {
              "FinInstnId": {
                "Othr": {
                  "Id": "INDOIDJA"
                }
              }
            }
          }
        },
        "Regn": {
          "RegnTp": "NEWR",
          "Prxy": {
            "Tp": "02",
            "Val": "frans.mazhar@gmail.com"
          },
          "PrxyRegn": {
            "DsplNm": "Oom Frans",
            "Agt": {
              "FinInstnId": {
                "Othr": {
                  "Id": "INDOIDJA"
                }
              }
            },
            "Acct": {
              "Id": {
                "Othr": {
                  "Id": "1234556"
                }
              },
              "Tp": {
                "Prtry": "SVGS"
              },
              "Nm": "Frans Mazhar"
            },
            "ScndId": {
              "Tp": "01",
              "Val": "44443333"
            },
            "RegnSts": "ACTV"
          }
        },
        "SplmtryData": [
          {
            "Envlp": {
              "Cstmr": {
                "Tp": "01",
                "Id": "220000022",
                "RsdntSts": "01",
                "TwnNm": "0300"
              }
            }
          }
        ]
      }
    }
  }
}

###

POST http://localhost:9006/mock/cihub HTTP/1.1
Content-Type: application/json

{"BusMsg":{"AppHdr":{"Fr":{"Fiid":{"FinInstnId":{"Othr":{"Id":"FASTIDJA"}}}},"To":{"Fiid":{"FinInstnId":{"Othr":{"Id":"ACTKIDJA"}}}},"BizMsgIdr":"20210826FASTIDJA510O0100000187","MsgDefIdr":"pacs.008.001.08","CreDt":"2021-08-26T21:38:22"},"Document":{"FitoFICstmrCdtTrf":{"GrpHdr":{"MsgId":"20210826FASTIDJA51000000188","CreDtTm":"2021-08-26T21:38:22","NbOfTxs":"1","SttlmInf":{"SttlmMtd":"CLRG"}},"CdtTrfTxInf":[{"PmtId":{"EndToEndId":"20210826FASTIDJA510O0100000187","TxId":"20210826FASTIDJA51000000188"},"IntrBkSttlmAmt":{"Value":"5000000.00","Ccy":"IDR"},"ChrgBr":"DEBT","Dbtr":{},"DbtrAgt":{"FinInstnId":{"Othr":{"Id":"FASTIDJA"}}},"CdtrAgt":{"FinInstnId":{"Othr":{"Id":"ACTKIDJA"}}},"Cdtr":{},"CdtrAcct":{"Id":{"Othr":{"Id":"44523871"}}}}]}}}}